### ISSUE TITLE
How can I achieve disabled state for the dropdown?

### ISSUE THREAD

**Issue by zukilover** [jseppi/angular-dropdowns#22]
The title says it all. Those jQuery plugins have it, is there any chance that it will be implemented to this too? How can I achieve such effect for now?

**Comment by yarivdev** [comment]
anything new? this would be a very nice addition.

**Comment by jseppi** [comment]
Pull requests are welcome!

**Comment by jseppi** [comment]
As of version 1.2.0, the `dropdown-disabled` setting has been added thanks to @Chinokao.

**Comment by asso1985** [comment]
Seems like not working to me, is not disabled if i put dropdown-disabled="true" or false

**Comment by jseppi** [comment]
@asso1985 can you make a [jsFiddle](https://jsfiddle.net/) showing your problem? It seems to work on my example page http://jseppi.github.io/angular-dropdowns/ (click the Disable All) button.

**Comment by asso1985** [comment]
Just checked my package.json and found out this :

{
  "name": "ng-dialog",
  "version": "0.5.6",
  "homepage": "https://github.com/likeastore/ngDialog",
  "description": "Modal dialogs and popups provider for Angular.js applications",
  "main": "./js/ngDialog.js",
  "scripts": {
    "pretest": "npm install && bower install --allow-root",
    "test": "./node_modules/karma/bin/karma start --single-run --browsers PhantomJS",
    "test-min": "./node_modules/karma/bin/karma start --single-run --browsers PhantomJS --min",
    "test-watch": "./node_modules/karma/bin/karma start --auto-watch --browsers PhantomJS",
    "serve": "node server",
    "webdriver-update": "node_modules/.bin/webdriver-manager update --standalone",
    "webdriver": "node_modules/.bin/webdriver-manager start",
    "preprotractor": "npm install && bower install --allow-root",
    "protractor": "node_modules/.bin/protractor protractor.conf.js",
    "protractor-a11y": "node_modules/.bin/protractor protractor.conf.js --a11y",
    "protractor-console": "node_modules/.bin/protractor protractor.conf.js --console-error"
  },
  "directories": {
    "test": "tests"
  },


Seems like i'm running version   "version": "0.5.6", that might be the problem.
