### ISSUE TITLE
link element to controller

### ISSUE THREAD

**Issue by vesparny** [jseppi/angular-dropdowns#42]
Hi,

what's the point of this line?
https://github.com/jseppi/angular-dropdowns/blob/master/angular-dropdowns.js#L142

Was wondering if the solution in thtis answer would be another possible solution.
http://stackoverflow.com/questions/18920644/angularjs-link-element-to-controller-in-directive

Is this a way to attach controller to template?

**Comment by jseppi** [comment]
Because the `dropdown-menu` directive wraps the original DOM element with another div, the directive controller cannot be specified in the directive definition. The solution in that StackOverflow question might also work.

**Comment by vesparny** [comment]
Could you point me out on the angular's documentation about how to bind controller to template using your method?

Didn't aware about that and it's pretty cool.

Thanks.

**Comment by jseppi** [comment]
I think I most likely saw that method in another library (though it has been a long time and I don't remember when or where), and not in the angular documentation. Sorry!

**Comment by vesparny** [comment]
As usual finding something in the angular documentation will be a pain ;)
