### ISSUE TITLE
Multiple Instance - ng-model collision.

### ISSUE THREAD

**Issue by dgtlmonk** [jseppi/angular-dropdowns#43]
What if you have multiple instance of the directive? I think you need to have unique model for each instance?  Maybe add an ID isolate scope and prefix the id to the model name per  instance, so the model don't collide?

**Comment by jseppi** [comment]
If you use one model across multiple directives they should stay linked in my opinion. That's what data binding is all about.
If you don't want your models linked then I think you should use separate models.
Or am I missing what you are saying? Providing an example on jsFiddle is helpful when filing issues.
