### ISSUE TITLE
Trigger dropwdown-onchange when dropdown-model changed from outside

### ISSUE THREAD

**Issue by dfjmax** [jseppi/angular-dropdowns#45]
Hi!
Is being taken into account this feature?
I have the case where I need to change the value of a dropdown and then trigger the onchange method based on another combo selection.
Any help would be appreciated, thanks!

**Comment by jseppi** [comment]
Could you just do that outside of the dropdown by placing a `$watch` on the value?

**Comment by dfjmax** [comment]
Yeah, you are right. I solved it anyway by calling the onchange method directly when the other combo changes. Thanks for your quick response!
