### ISSUE TITLE
dropdownItemLabel from attrs not scope

### ISSUE THREAD

**Issue by BDomzalski** [jseppi/angular-dropdowns#50]
Hi,
I have a specific use of the dropdownSelect. I need to manually compile and link an element with this directive but I have an issue which is connected to dropdownItemLabel attribute. The value of labelField is taken from that attribute and in my case this is a problem because I would like it to be $interpolated and this implementation prevents it from doing so.
Why this isn't passed as a property of the scope of dropdownSelect? Is there a perticular reason?

Regards,
Bartosz Domżalski

**Comment by jseppi** [comment]
I can't think of any reason why a scoped variable wouldn't work, so feel free to submit a pull request with the modification! Thanks!

**Comment by jseppi** [comment]
Closed in 8ba892be870ffa4bf7859a259623d960e0883a5b
