### ISSUE TITLE
Changing of selected item

### ISSUE THREAD

**Issue by pistolete** [jseppi/angular-dropdowns#54]
'dropdownMenu' and 'dropdownSelect' directives has a following code
```javascript
          if (selected !== $scope.dropdownModel) {
            angular.copy(selected, $scope.dropdownModel);
          }
```
There is two troubles.
1. angular.copy ignores $$hashKey attribute, as the result we have a mixing objects. Why not explicit assignment?
2. should be used for comparision angular.equals

As result:
```javascript
          if (!angular.equals(selected, $scope.dropdownModel)) {
              $scope.dropdownModel = selected;
          }
```

**Comment by jseppi** [comment]
Thanks. I'd happily review a pull request.
