### ISSUE TITLE
Not able to use angular-translate with angular-dropdowns

### ISSUE THREAD

**Issue by mukulgupta2507** [jseppi/angular-dropdowns#56]
Hi,

I'm using angular-dropdowns in my project and it's working seamlessly so far. I'm not able to figure out how to use angular-translate with dropdown options. I have used angular-translate in other view using:
 
```{{someText|translate}} ```

but not now since I'm giving an array of options with their corresponsing values as described in the examples. Can anyone please tell me how can I use angular-translate here in this scenario ?

Scenario from the given example:

```
app.controller('AppCtrl', function($scope) {

    // By default the 'text' property will be used as the display text in the dropdown entry.
    // All options that are not dividers must have a 'text' property.
    // You can specify a different property name in place of 'text' via the dropdown-item-label attribute.
    // A divider with a 'text' property will also be non-selectable.
    //
    // If an options object has an 'href' property set, then that dropdown entry
    //   will behave as a link and cannot be selected.
    $scope.ddSelectOptions = [
        {
            text: 'Option1',
            value: 'a value'
        },
        {
            text: 'Option2',
            value: 'another value'
        }
    ];

    $scope.ddSelectSelected = {}; // Must be an object
});
```

Now, if I want to translate Option1 and Option2 using angular translate in my controller/view, how can I do it?

P.S: I tried my regular approach by using 
```
{{"Option1"|translate}} and {{"Option12"|translate}} 
```

```
app.controller('AppCtrl', function($scope) {

    // By default the 'text' property will be used as the display text in the dropdown entry.
    // All options that are not dividers must have a 'text' property.
    // You can specify a different property name in place of 'text' via the dropdown-item-label attribute.
    // A divider with a 'text' property will also be non-selectable.
    //
    // If an options object has an 'href' property set, then that dropdown entry
    //   will behave as a link and cannot be selected.
    $scope.ddSelectOptions = [
        {
            text: '{{Option1|translate}}',
            value: 'a value'
        },
        {
            text: '{{Option2|translate}}',
            value: 'another value'
        }
    ];

    $scope.ddSelectSelected = {}; // Must be an object
});
```

but somehow that is also not working. 

Can anyone please help me with this ?

Thanks

**Comment by jseppi** [comment]
You will have to manually call angular-translate's methods and update the values in the `ddSelectOptions` object. It looks like the `$translate` service is what you should use: https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate

**Comment by mukulgupta2507** [comment]
Hi Jseppi,

I tried using $translate service but issue is it's not working in this case:

```
    $translate(Option1)
      .then(function (translatedOption1) {
        $scope.Option1AfterTranslation = translatedOption1;
      });

    $scope.ddSelectOptions = [
        {
            text: $scope.Option1AfterTranslation,    ---> gives undefined in the dropdown option
            value: 'a value'
        }
    ];
```

Any idea where I'm doing wrong?
I'm just starting with learning angular stuff. Forgive me if I'm missing something very basic.
I do appreciate your help in the issue.

**Comment by DhruvPrakash** [comment]
Hi mukul,
Assuming option1 and option2 contains the labels you want translated,
you can try using the translate filter directly in your controller.
```
app.controller('AppCtrl', function($scope,$filter) {
$scope.ddSelectOptions = [
        {
            text: $filter('translate')(option1),
            value: 'a value'
        },
        {
            text: $filter('translate')(option2),
            value: 'another value'
        }
    ];
   
```

**Comment by jseppi** [comment]
Thanks for the help, @DhruvPrakash!
