### ISSUE TITLE
Modifying dropdownMenu wrap element

### ISSUE THREAD

**Issue by handonam** [jseppi/angular-dropdowns#68]
There's a line on 153 for directive `dropdownMenu` that has this:
```javascript
var $wrap = $compile(angular.element(
  '<div class="wrap-dd-menu" ng-class="{\'disabled\': dropdownDisabled}"></div>')
)($scope);
```

it seems a bit too rigid, and we can't modify it.  `dropdownSelect` seems to have this built into the templateCache.  Shouldn't the menu's wrap be moved out to templateCache as well?

**Comment by jseppi** [comment]
Great idea! If you can do a PR I'll review and merge it in.
