### ISSUE TITLE
Dropdown validation

### ISSUE THREAD

**Issue by ThapaMahesh** [jseppi/angular-dropdowns#72]
How do we validate this dropdown as required in a from?

**Comment by jseppi** [comment]
You might be able to wrap it in another directive that implements a custom form control as described at the bottom of this page: https://docs.angularjs.org/guide/forms

**Comment by ThapaMahesh** [comment]
It would have been great if the plugin would do some validation. Well Thanks I was able to do so implementing custom directive.
