### ISSUE TITLE
Support for ng-class attribute

### ISSUE THREAD

**Issue by mathilde-pellerin** [jseppi/angular-dropdowns#73]
Hi,

currently, using ng-class on the dropdown doesn't work because it is internally used. It result in something like that : 
`<div ng-class="{'am-input-error': configurator.dealerErrors.Dealer} {'disabled': dropdownDisabled}" ...>`

Do you think it would be possible to add support for ng-class, or to add an attribute allowing us to add css class dynamically depending a variable ? 
It should be very nice to error management.

Thanks

**Comment by jseppi** [comment]
There's actually not a great way to do this in angular. See this discussion: https://github.com/angular/angular.js/issues/5695

Perhaps the easiest solution for you would be to wrap the dropdown directive in another `<div>` and use your ng-class there.
