### ISSUE TITLE
Clear dropdown

### ISSUE THREAD

**Issue by sp90** [jseppi/angular-dropdowns#78]
Im  trying to clear the dropdown so if i selected an item and trying to reset it how do i do that?

**Comment by jseppi** [comment]
You could make use of the `dropdown-onchange` attribute to call a function that clears out your scope variable that holds the dropdown options object on change.

**Comment by sp90** [comment]
@jseppi i think we miss communicated there, i wanna clear my modal to its initial state by clicking a button, would you use onchange? aswell

**Comment by jseppi** [comment]
Use your button to call a function in your controller that changes the state of the dropdown config variable.
